-- AlterEnum: Add ANOMALOUS_LATERAL_MOVEMENT to AuditAction
ALTER TYPE "AuditAction" ADD VALUE 'ANOMALOUS_LATERAL_MOVEMENT';

-- AlterEnum: Add LATERAL_MOVEMENT_ALERT to NotificationType
ALTER TYPE "NotificationType" ADD VALUE 'LATERAL_MOVEMENT_ALERT';
