// Code generated by hand (equivalent to protoc-gen-go-grpc output).
// Source: proto/cache.proto
//
//go:generate protoc --go_out=. --go-grpc_out=. proto/cache.proto

package main

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Message types matching the proto definition.
// These are plain Go structs used with a JSON codec for gRPC.

type GetRequest struct {
	Key string `json:"key"`
}
type GetResponse struct {
	Value []byte `json:"value"`
	Found bool   `json:"found"`
}

type SetRequest struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
	TtlMs int64  `json:"ttl_ms"`
}
type SetResponse struct {
	Ok bool `json:"ok"`
}

type DeleteRequest struct {
	Key string `json:"key"`
}
type DeleteResponse struct {
	Deleted bool `json:"deleted"`
}

type IncrRequest struct {
	Key   string `json:"key"`
	Delta int64  `json:"delta"`
}
type IncrResponse struct {
	Value int64 `json:"value"`
}

type GetDelRequest struct {
	Key string `json:"key"`
}
type GetDelResponse struct {
	Value []byte `json:"value"`
	Found bool   `json:"found"`
}

type ExpireRequest struct {
	Key   string `json:"key"`
	TtlMs int64  `json:"ttl_ms"`
}
type ExpireResponse struct {
	Ok bool `json:"ok"`
}

type PublishRequest struct {
	Channel string `json:"channel"`
	Message []byte `json:"message"`
}
type PublishResponse struct {
	Receivers int32 `json:"receivers"`
}

type SubscribeRequest struct {
	Channel string `json:"channel"`
	Pattern bool   `json:"pattern"`
}
type SubscribeResponse struct {
	Channel string `json:"channel"`
	Message []byte `json:"message"`
}

type AcquireLockRequest struct {
	Name     string `json:"name"`
	TtlMs    int64  `json:"ttl_ms"`
	HolderId string `json:"holder_id"`
}
type AcquireLockResponse struct {
	Acquired     bool   `json:"acquired"`
	FencingToken uint64 `json:"fencing_token"`
}

type ReleaseLockRequest struct {
	Name     string `json:"name"`
	HolderId string `json:"holder_id"`
}
type ReleaseLockResponse struct {
	Released bool `json:"released"`
}

type RenewLockRequest struct {
	Name     string `json:"name"`
	TtlMs    int64  `json:"ttl_ms"`
	HolderId string `json:"holder_id"`
}
type RenewLockResponse struct {
	Renewed bool `json:"renewed"`
}

type EnqueueRequest struct {
	QueueName string `json:"queue_name"`
	Message   []byte `json:"message"`
}
type EnqueueResponse struct {
	Ok bool `json:"ok"`
}

type DequeueRequest struct {
	QueueName string `json:"queue_name"`
	TimeoutMs int64  `json:"timeout_ms"`
}
type DequeueResponse struct {
	Message []byte `json:"message"`
	Found   bool   `json:"found"`
}

type SnapshotRequest struct{}
type SnapshotEntry struct {
	Key       string `json:"key"`
	Value     []byte `json:"value"`
	TtlMs     int64  `json:"ttl_ms"`
	Timestamp uint64 `json:"timestamp"`
}
type SnapshotResponse struct {
	Entries []SnapshotEntry `json:"entries"`
}

type ReplicateKVRequest struct {
	Key       string `json:"key"`
	Value     []byte `json:"value"`
	TtlMs     int64  `json:"ttl_ms"`
	Deleted   bool   `json:"deleted"`
	Timestamp uint64 `json:"timestamp"`
}
type ReplicateKVResponse struct {
	Applied int32 `json:"applied"`
}

type ReplicatePubSubRequest struct {
	Channel string `json:"channel"`
	Message []byte `json:"message"`
}
type ReplicatePubSubResponse struct {
	Delivered int32 `json:"delivered"`
}

type HeartbeatRequest struct {
	PeerId  string `json:"peer_id"`
	Address string `json:"address"`
}
type HeartbeatResponse struct {
	PeerId string `json:"peer_id"`
	Ok     bool   `json:"ok"`
}

// CacheServiceServer is the server API for CacheService.
type CacheServiceServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Set(context.Context, *SetRequest) (*SetResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Incr(context.Context, *IncrRequest) (*IncrResponse, error)
	GetDel(context.Context, *GetDelRequest) (*GetDelResponse, error)
	Expire(context.Context, *ExpireRequest) (*ExpireResponse, error)
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	Subscribe(*SubscribeRequest, CacheService_SubscribeServer) error
	AcquireLock(context.Context, *AcquireLockRequest) (*AcquireLockResponse, error)
	ReleaseLock(context.Context, *ReleaseLockRequest) (*ReleaseLockResponse, error)
	RenewLock(context.Context, *RenewLockRequest) (*RenewLockResponse, error)
	Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error)
	Dequeue(context.Context, *DequeueRequest) (*DequeueResponse, error)
	GetSnapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	ReplicateKV(CacheService_ReplicateKVServer) error
	ReplicatePubSub(CacheService_ReplicatePubSubServer) error
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
}

// UnimplementedCacheServiceServer provides default implementations.
type UnimplementedCacheServiceServer struct{}

func (UnimplementedCacheServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCacheServiceServer) Set(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedCacheServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCacheServiceServer) Incr(context.Context, *IncrRequest) (*IncrResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Incr not implemented")
}
func (UnimplementedCacheServiceServer) GetDel(context.Context, *GetDelRequest) (*GetDelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDel not implemented")
}
func (UnimplementedCacheServiceServer) Expire(context.Context, *ExpireRequest) (*ExpireResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Expire not implemented")
}
func (UnimplementedCacheServiceServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedCacheServiceServer) Subscribe(*SubscribeRequest, CacheService_SubscribeServer) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedCacheServiceServer) AcquireLock(context.Context, *AcquireLockRequest) (*AcquireLockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcquireLock not implemented")
}
func (UnimplementedCacheServiceServer) ReleaseLock(context.Context, *ReleaseLockRequest) (*ReleaseLockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseLock not implemented")
}
func (UnimplementedCacheServiceServer) RenewLock(context.Context, *RenewLockRequest) (*RenewLockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewLock not implemented")
}
func (UnimplementedCacheServiceServer) Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enqueue not implemented")
}
func (UnimplementedCacheServiceServer) Dequeue(context.Context, *DequeueRequest) (*DequeueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Dequeue not implemented")
}
func (UnimplementedCacheServiceServer) GetSnapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedCacheServiceServer) ReplicateKV(CacheService_ReplicateKVServer) error {
	return status.Error(codes.Unimplemented, "method ReplicateKV not implemented")
}
func (UnimplementedCacheServiceServer) ReplicatePubSub(CacheService_ReplicatePubSubServer) error {
	return status.Error(codes.Unimplemented, "method ReplicatePubSub not implemented")
}
func (UnimplementedCacheServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}

// Stream interfaces for server-streaming and client-streaming RPCs.

type CacheService_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type cacheServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *cacheServiceSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

type CacheService_ReplicateKVServer interface {
	SendAndClose(*ReplicateKVResponse) error
	Recv() (*ReplicateKVRequest, error)
	grpc.ServerStream
}

type cacheServiceReplicateKVServer struct {
	grpc.ServerStream
}

func (x *cacheServiceReplicateKVServer) SendAndClose(m *ReplicateKVResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cacheServiceReplicateKVServer) Recv() (*ReplicateKVRequest, error) {
	m := new(ReplicateKVRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

type CacheService_ReplicatePubSubServer interface {
	SendAndClose(*ReplicatePubSubResponse) error
	Recv() (*ReplicatePubSubRequest, error)
	grpc.ServerStream
}

type cacheServiceReplicatePubSubServer struct {
	grpc.ServerStream
}

func (x *cacheServiceReplicatePubSubServer) SendAndClose(m *ReplicatePubSubResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cacheServiceReplicatePubSubServer) Recv() (*ReplicatePubSubRequest, error) {
	m := new(ReplicatePubSubRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Service descriptor and registration.

var _CacheService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cache.CacheService",
	HandlerType: (*CacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "Get", Handler: _CacheService_Get_Handler},
		{MethodName: "Set", Handler: _CacheService_Set_Handler},
		{MethodName: "Delete", Handler: _CacheService_Delete_Handler},
		{MethodName: "Incr", Handler: _CacheService_Incr_Handler},
		{MethodName: "GetDel", Handler: _CacheService_GetDel_Handler},
		{MethodName: "Expire", Handler: _CacheService_Expire_Handler},
		{MethodName: "Publish", Handler: _CacheService_Publish_Handler},
		{MethodName: "AcquireLock", Handler: _CacheService_AcquireLock_Handler},
		{MethodName: "ReleaseLock", Handler: _CacheService_ReleaseLock_Handler},
		{MethodName: "RenewLock", Handler: _CacheService_RenewLock_Handler},
		{MethodName: "Enqueue", Handler: _CacheService_Enqueue_Handler},
		{MethodName: "Dequeue", Handler: _CacheService_Dequeue_Handler},
		{MethodName: "GetSnapshot", Handler: _CacheService_GetSnapshot_Handler},
		{MethodName: "Heartbeat", Handler: _CacheService_Heartbeat_Handler},
	},
	Streams: []grpc.StreamDesc{
		{StreamName: "Subscribe", Handler: _CacheService_Subscribe_Handler, ServerStreams: true},
		{StreamName: "ReplicateKV", Handler: _CacheService_ReplicateKV_Handler, ClientStreams: true},
		{StreamName: "ReplicatePubSub", Handler: _CacheService_ReplicatePubSub_Handler, ClientStreams: true},
	},
	Metadata: "proto/cache.proto",
}

// RegisterCacheServiceServer registers the server implementation.
func RegisterCacheServiceServer(s *grpc.Server, srv CacheServiceServer) {
	s.RegisterService(&_CacheService_serviceDesc, srv)
}

// Method handlers.

func _CacheService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/Get"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Get(ctx, req.(*GetRequest))
	})
}

func _CacheService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/Set"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Set(ctx, req.(*SetRequest))
	})
}

func _CacheService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/Delete"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Delete(ctx, req.(*DeleteRequest))
	})
}

func _CacheService_Incr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Incr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/Incr"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Incr(ctx, req.(*IncrRequest))
	})
}

func _CacheService_GetDel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).GetDel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/GetDel"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).GetDel(ctx, req.(*GetDelRequest))
	})
}

func _CacheService_Expire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpireRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Expire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/Expire"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Expire(ctx, req.(*ExpireRequest))
	})
}

func _CacheService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/Publish"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Publish(ctx, req.(*PublishRequest))
	})
}

func _CacheService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CacheServiceServer).Subscribe(m, &cacheServiceSubscribeServer{stream})
}

func _CacheService_AcquireLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).AcquireLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/AcquireLock"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).AcquireLock(ctx, req.(*AcquireLockRequest))
	})
}

func _CacheService_ReleaseLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).ReleaseLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/ReleaseLock"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).ReleaseLock(ctx, req.(*ReleaseLockRequest))
	})
}

func _CacheService_RenewLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).RenewLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/RenewLock"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).RenewLock(ctx, req.(*RenewLockRequest))
	})
}

func _CacheService_Enqueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Enqueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/Enqueue"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Enqueue(ctx, req.(*EnqueueRequest))
	})
}

func _CacheService_Dequeue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DequeueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Dequeue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/Dequeue"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Dequeue(ctx, req.(*DequeueRequest))
	})
}

func _CacheService_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/GetSnapshot"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).GetSnapshot(ctx, req.(*SnapshotRequest))
	})
}

func _CacheService_ReplicateKV_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CacheServiceServer).ReplicateKV(&cacheServiceReplicateKVServer{stream})
}

func _CacheService_ReplicatePubSub_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CacheServiceServer).ReplicatePubSub(&cacheServiceReplicatePubSubServer{stream})
}

func _CacheService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/cache.CacheService/Heartbeat"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	})
}
