ALTER TYPE public."AuditAction"
ADD VALUE IF NOT EXISTS 'FILE_UPLOAD';

ALTER TYPE public."AuditAction"
ADD VALUE IF NOT EXISTS 'FILE_DOWNLOAD';

ALTER TYPE public."AuditAction"
ADD VALUE IF NOT EXISTS 'FILE_DELETE';

ALTER TYPE public."AuditAction"
ADD VALUE IF NOT EXISTS 'FILE_MKDIR';

ALTER TYPE public."AuditAction"
ADD VALUE IF NOT EXISTS 'FILE_RENAME';

ALTER TYPE public."AuditAction"
ADD VALUE IF NOT EXISTS 'FILE_LIST';
