ALTER TYPE public."SessionStatus"
ADD VALUE IF NOT EXISTS 'PAUSED';

ALTER TYPE public."AuditAction"
ADD VALUE IF NOT EXISTS 'SESSION_PAUSE';

ALTER TYPE public."AuditAction"
ADD VALUE IF NOT EXISTS 'SESSION_RESUME';
