// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package orchestrationdb

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccessPolicyTargetType string

const (
	AccessPolicyTargetTypeTENANT AccessPolicyTargetType = "TENANT"
	AccessPolicyTargetTypeTEAM   AccessPolicyTargetType = "TEAM"
	AccessPolicyTargetTypeFOLDER AccessPolicyTargetType = "FOLDER"
)

func (e *AccessPolicyTargetType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccessPolicyTargetType(s)
	case string:
		*e = AccessPolicyTargetType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccessPolicyTargetType: %T", src)
	}
	return nil
}

type NullAccessPolicyTargetType struct {
	AccessPolicyTargetType AccessPolicyTargetType
	Valid                  bool // Valid is true if AccessPolicyTargetType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccessPolicyTargetType) Scan(value interface{}) error {
	if value == nil {
		ns.AccessPolicyTargetType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccessPolicyTargetType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccessPolicyTargetType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccessPolicyTargetType), nil
}

type AuditAction string

const (
	AuditActionLOGIN                            AuditAction = "LOGIN"
	AuditActionLOGINOAUTH                       AuditAction = "LOGIN_OAUTH"
	AuditActionLOGINTOTP                        AuditAction = "LOGIN_TOTP"
	AuditActionLOGOUT                           AuditAction = "LOGOUT"
	AuditActionREGISTER                         AuditAction = "REGISTER"
	AuditActionVAULTUNLOCK                      AuditAction = "VAULT_UNLOCK"
	AuditActionVAULTLOCK                        AuditAction = "VAULT_LOCK"
	AuditActionVAULTSETUP                       AuditAction = "VAULT_SETUP"
	AuditActionCREATECONNECTION                 AuditAction = "CREATE_CONNECTION"
	AuditActionUPDATECONNECTION                 AuditAction = "UPDATE_CONNECTION"
	AuditActionDELETECONNECTION                 AuditAction = "DELETE_CONNECTION"
	AuditActionSHARECONNECTION                  AuditAction = "SHARE_CONNECTION"
	AuditActionUNSHARECONNECTION                AuditAction = "UNSHARE_CONNECTION"
	AuditActionUPDATESHAREPERMISSION            AuditAction = "UPDATE_SHARE_PERMISSION"
	AuditActionCREATEFOLDER                     AuditAction = "CREATE_FOLDER"
	AuditActionUPDATEFOLDER                     AuditAction = "UPDATE_FOLDER"
	AuditActionDELETEFOLDER                     AuditAction = "DELETE_FOLDER"
	AuditActionPASSWORDCHANGE                   AuditAction = "PASSWORD_CHANGE"
	AuditActionPROFILEUPDATE                    AuditAction = "PROFILE_UPDATE"
	AuditActionTOTPENABLE                       AuditAction = "TOTP_ENABLE"
	AuditActionTOTPDISABLE                      AuditAction = "TOTP_DISABLE"
	AuditActionLOGINSMS                         AuditAction = "LOGIN_SMS"
	AuditActionSMSMFAENABLE                     AuditAction = "SMS_MFA_ENABLE"
	AuditActionSMSMFADISABLE                    AuditAction = "SMS_MFA_DISABLE"
	AuditActionSMSPHONEVERIFY                   AuditAction = "SMS_PHONE_VERIFY"
	AuditActionOAUTHLINK                        AuditAction = "OAUTH_LINK"
	AuditActionOAUTHUNLINK                      AuditAction = "OAUTH_UNLINK"
	AuditActionPASSWORDREVEAL                   AuditAction = "PASSWORD_REVEAL"
	AuditActionTENANTCREATE                     AuditAction = "TENANT_CREATE"
	AuditActionTENANTUPDATE                     AuditAction = "TENANT_UPDATE"
	AuditActionTENANTDELETE                     AuditAction = "TENANT_DELETE"
	AuditActionTENANTINVITEUSER                 AuditAction = "TENANT_INVITE_USER"
	AuditActionTENANTREMOVEUSER                 AuditAction = "TENANT_REMOVE_USER"
	AuditActionTENANTUPDATEUSERROLE             AuditAction = "TENANT_UPDATE_USER_ROLE"
	AuditActionTEAMCREATE                       AuditAction = "TEAM_CREATE"
	AuditActionTEAMUPDATE                       AuditAction = "TEAM_UPDATE"
	AuditActionTEAMDELETE                       AuditAction = "TEAM_DELETE"
	AuditActionTEAMADDMEMBER                    AuditAction = "TEAM_ADD_MEMBER"
	AuditActionTEAMREMOVEMEMBER                 AuditAction = "TEAM_REMOVE_MEMBER"
	AuditActionTEAMUPDATEMEMBERROLE             AuditAction = "TEAM_UPDATE_MEMBER_ROLE"
	AuditActionEMAILTESTSEND                    AuditAction = "EMAIL_TEST_SEND"
	AuditActionGATEWAYCREATE                    AuditAction = "GATEWAY_CREATE"
	AuditActionGATEWAYUPDATE                    AuditAction = "GATEWAY_UPDATE"
	AuditActionGATEWAYDELETE                    AuditAction = "GATEWAY_DELETE"
	AuditActionSSHKEYGENERATE                   AuditAction = "SSH_KEY_GENERATE"
	AuditActionSSHKEYROTATE                     AuditAction = "SSH_KEY_ROTATE"
	AuditActionBATCHSHARE                       AuditAction = "BATCH_SHARE"
	AuditActionSSHKEYAUTOROTATE                 AuditAction = "SSH_KEY_AUTO_ROTATE"
	AuditActionSESSIONSTART                     AuditAction = "SESSION_START"
	AuditActionSESSIONEND                       AuditAction = "SESSION_END"
	AuditActionLOGINFAILURE                     AuditAction = "LOGIN_FAILURE"
	AuditActionSSHKEYPUSH                       AuditAction = "SSH_KEY_PUSH"
	AuditActionSECRETCREATE                     AuditAction = "SECRET_CREATE"
	AuditActionSECRETREAD                       AuditAction = "SECRET_READ"
	AuditActionSECRETUPDATE                     AuditAction = "SECRET_UPDATE"
	AuditActionSECRETDELETE                     AuditAction = "SECRET_DELETE"
	AuditActionSECRETSHARE                      AuditAction = "SECRET_SHARE"
	AuditActionSECRETUNSHARE                    AuditAction = "SECRET_UNSHARE"
	AuditActionSECRETEXTERNALSHARE              AuditAction = "SECRET_EXTERNAL_SHARE"
	AuditActionSECRETEXTERNALACCESS             AuditAction = "SECRET_EXTERNAL_ACCESS"
	AuditActionSECRETVERSIONRESTORE             AuditAction = "SECRET_VERSION_RESTORE"
	AuditActionTENANTVAULTINIT                  AuditAction = "TENANT_VAULT_INIT"
	AuditActionTENANTVAULTKEYDISTRIBUTE         AuditAction = "TENANT_VAULT_KEY_DISTRIBUTE"
	AuditActionSESSIONTIMEOUT                   AuditAction = "SESSION_TIMEOUT"
	AuditActionGATEWAYDEPLOY                    AuditAction = "GATEWAY_DEPLOY"
	AuditActionGATEWAYUNDEPLOY                  AuditAction = "GATEWAY_UNDEPLOY"
	AuditActionGATEWAYSCALE                     AuditAction = "GATEWAY_SCALE"
	AuditActionGATEWAYRESTART                   AuditAction = "GATEWAY_RESTART"
	AuditActionGATEWAYHEALTHCHECK               AuditAction = "GATEWAY_HEALTH_CHECK"
	AuditActionGATEWAYSCALEUP                   AuditAction = "GATEWAY_SCALE_UP"
	AuditActionGATEWAYSCALEDOWN                 AuditAction = "GATEWAY_SCALE_DOWN"
	AuditActionTENANTMFAPOLICYUPDATE            AuditAction = "TENANT_MFA_POLICY_UPDATE"
	AuditActionGATEWAYTEMPLATECREATE            AuditAction = "GATEWAY_TEMPLATE_CREATE"
	AuditActionGATEWAYTEMPLATEUPDATE            AuditAction = "GATEWAY_TEMPLATE_UPDATE"
	AuditActionGATEWAYTEMPLATEDELETE            AuditAction = "GATEWAY_TEMPLATE_DELETE"
	AuditActionGATEWAYTEMPLATEDEPLOY            AuditAction = "GATEWAY_TEMPLATE_DEPLOY"
	AuditActionREFRESHTOKENREUSE                AuditAction = "REFRESH_TOKEN_REUSE"
	AuditActionGATEWAYVIEWLOGS                  AuditAction = "GATEWAY_VIEW_LOGS"
	AuditActionSESSIONERROR                     AuditAction = "SESSION_ERROR"
	AuditActionSFTPUPLOAD                       AuditAction = "SFTP_UPLOAD"
	AuditActionSFTPDOWNLOAD                     AuditAction = "SFTP_DOWNLOAD"
	AuditActionSFTPDELETE                       AuditAction = "SFTP_DELETE"
	AuditActionSFTPMKDIR                        AuditAction = "SFTP_MKDIR"
	AuditActionSFTPRENAME                       AuditAction = "SFTP_RENAME"
	AuditActionVAULTAUTOLOCK                    AuditAction = "VAULT_AUTO_LOCK"
	AuditActionSESSIONTERMINATE                 AuditAction = "SESSION_TERMINATE"
	AuditActionSECRETEXTERNALREVOKE             AuditAction = "SECRET_EXTERNAL_REVOKE"
	AuditActionSECRETSHAREUPDATE                AuditAction = "SECRET_SHARE_UPDATE"
	AuditActionGATEWAYRECONCILE                 AuditAction = "GATEWAY_RECONCILE"
	AuditActionCONNECTIONFAVORITE               AuditAction = "CONNECTION_FAVORITE"
	AuditActionWEBAUTHNREGISTER                 AuditAction = "WEBAUTHN_REGISTER"
	AuditActionWEBAUTHNREMOVE                   AuditAction = "WEBAUTHN_REMOVE"
	AuditActionLOGINWEBAUTHN                    AuditAction = "LOGIN_WEBAUTHN"
	AuditActionPASSWORDRESETREQUEST             AuditAction = "PASSWORD_RESET_REQUEST"
	AuditActionPASSWORDRESETCOMPLETE            AuditAction = "PASSWORD_RESET_COMPLETE"
	AuditActionPASSWORDRESETFAILURE             AuditAction = "PASSWORD_RESET_FAILURE"
	AuditActionVAULTRECOVERYKEYGENERATED        AuditAction = "VAULT_RECOVERY_KEY_GENERATED"
	AuditActionVAULTRESET                       AuditAction = "VAULT_RESET"
	AuditActionTENANTCREATEUSER                 AuditAction = "TENANT_CREATE_USER"
	AuditActionTENANTTOGGLEUSER                 AuditAction = "TENANT_TOGGLE_USER"
	AuditActionAPPCONFIGUPDATE                  AuditAction = "APP_CONFIG_UPDATE"
	AuditActionPROFILEEMAILCHANGE               AuditAction = "PROFILE_EMAIL_CHANGE"
	AuditActionADMINEMAILCHANGE                 AuditAction = "ADMIN_EMAIL_CHANGE"
	AuditActionADMINPASSWORDCHANGE              AuditAction = "ADMIN_PASSWORD_CHANGE"
	AuditActionDOMAINPROFILEUPDATE              AuditAction = "DOMAIN_PROFILE_UPDATE"
	AuditActionDOMAINPROFILECLEAR               AuditAction = "DOMAIN_PROFILE_CLEAR"
	AuditActionTENANTSWITCH                     AuditAction = "TENANT_SWITCH"
	AuditActionRECORDINGSTART                   AuditAction = "RECORDING_START"
	AuditActionRECORDINGVIEW                    AuditAction = "RECORDING_VIEW"
	AuditActionRECORDINGDELETE                  AuditAction = "RECORDING_DELETE"
	AuditActionRECORDINGEXPORTVIDEO             AuditAction = "RECORDING_EXPORT_VIDEO"
	AuditActionEXPORTCONNECTIONS                AuditAction = "EXPORT_CONNECTIONS"
	AuditActionIMPORTCONNECTIONS                AuditAction = "IMPORT_CONNECTIONS"
	AuditActionTENANTMEMBERSHIPEXPIRED          AuditAction = "TENANT_MEMBERSHIP_EXPIRED"
	AuditActionTEAMMEMBERSHIPEXPIRED            AuditAction = "TEAM_MEMBERSHIP_EXPIRED"
	AuditActionTENANTMEMBERSHIPEXPIRYUPDATE     AuditAction = "TENANT_MEMBERSHIP_EXPIRY_UPDATE"
	AuditActionTEAMMEMBERSHIPEXPIRYUPDATE       AuditAction = "TEAM_MEMBERSHIP_EXPIRY_UPDATE"
	AuditActionTENANTDLPPOLICYUPDATE            AuditAction = "TENANT_DLP_POLICY_UPDATE"
	AuditActionTOKENHIJACKATTEMPT               AuditAction = "TOKEN_HIJACK_ATTEMPT"
	AuditActionTENANTCONNECTIONPOLICYUPDATE     AuditAction = "TENANT_CONNECTION_POLICY_UPDATE"
	AuditActionSESSIONLIMITEXCEEDED             AuditAction = "SESSION_LIMIT_EXCEEDED"
	AuditActionSESSIONABSOLUTETIMEOUT           AuditAction = "SESSION_ABSOLUTE_TIMEOUT"
	AuditActionVAULTPROVIDERCREATE              AuditAction = "VAULT_PROVIDER_CREATE"
	AuditActionVAULTPROVIDERUPDATE              AuditAction = "VAULT_PROVIDER_UPDATE"
	AuditActionVAULTPROVIDERDELETE              AuditAction = "VAULT_PROVIDER_DELETE"
	AuditActionVAULTPROVIDERTEST                AuditAction = "VAULT_PROVIDER_TEST"
	AuditActionLDAPLOGIN                        AuditAction = "LDAP_LOGIN"
	AuditActionLDAPLOGINFAILURE                 AuditAction = "LDAP_LOGIN_FAILURE"
	AuditActionLDAPSYNCSTART                    AuditAction = "LDAP_SYNC_START"
	AuditActionLDAPSYNCCOMPLETE                 AuditAction = "LDAP_SYNC_COMPLETE"
	AuditActionLDAPSYNCERROR                    AuditAction = "LDAP_SYNC_ERROR"
	AuditActionLDAPUSERCREATED                  AuditAction = "LDAP_USER_CREATED"
	AuditActionLDAPUSERDISABLED                 AuditAction = "LDAP_USER_DISABLED"
	AuditActionSYNCPROFILECREATE                AuditAction = "SYNC_PROFILE_CREATE"
	AuditActionSYNCPROFILEUPDATE                AuditAction = "SYNC_PROFILE_UPDATE"
	AuditActionSYNCPROFILEDELETE                AuditAction = "SYNC_PROFILE_DELETE"
	AuditActionSYNCSTART                        AuditAction = "SYNC_START"
	AuditActionSYNCCOMPLETE                     AuditAction = "SYNC_COMPLETE"
	AuditActionSYNCERROR                        AuditAction = "SYNC_ERROR"
	AuditActionIMPOSSIBLETRAVELDETECTED         AuditAction = "IMPOSSIBLE_TRAVEL_DETECTED"
	AuditActionTUNNELCONNECT                    AuditAction = "TUNNEL_CONNECT"
	AuditActionTUNNELDISCONNECT                 AuditAction = "TUNNEL_DISCONNECT"
	AuditActionTUNNELTOKENGENERATE              AuditAction = "TUNNEL_TOKEN_GENERATE"
	AuditActionTUNNELTOKENROTATE                AuditAction = "TUNNEL_TOKEN_ROTATE"
	AuditActionSESSIONDENIEDABAC                AuditAction = "SESSION_DENIED_ABAC"
	AuditActionSESSIONTERMINATEDPOLICYVIOLATION AuditAction = "SESSION_TERMINATED_POLICY_VIOLATION"
	AuditActionKEYSTROKEPOLICYCREATE            AuditAction = "KEYSTROKE_POLICY_CREATE"
	AuditActionKEYSTROKEPOLICYUPDATE            AuditAction = "KEYSTROKE_POLICY_UPDATE"
	AuditActionKEYSTROKEPOLICYDELETE            AuditAction = "KEYSTROKE_POLICY_DELETE"
	AuditActionSECRETCHECKOUTREQUESTED          AuditAction = "SECRET_CHECKOUT_REQUESTED"
	AuditActionSECRETCHECKOUTAPPROVED           AuditAction = "SECRET_CHECKOUT_APPROVED"
	AuditActionSECRETCHECKOUTDENIED             AuditAction = "SECRET_CHECKOUT_DENIED"
	AuditActionSECRETCHECKOUTEXPIRED            AuditAction = "SECRET_CHECKOUT_EXPIRED"
	AuditActionSECRETCHECKOUTCHECKEDIN          AuditAction = "SECRET_CHECKOUT_CHECKED_IN"
	AuditActionPASSWORDROTATIONSUCCESS          AuditAction = "PASSWORD_ROTATION_SUCCESS"
	AuditActionPASSWORDROTATIONFAILED           AuditAction = "PASSWORD_ROTATION_FAILED"
	AuditActionDEVICEAUTHINITIATED              AuditAction = "DEVICE_AUTH_INITIATED"
	AuditActionDEVICEAUTHCOMPLETED              AuditAction = "DEVICE_AUTH_COMPLETED"
	AuditActionANOMALOUSLATERALMOVEMENT         AuditAction = "ANOMALOUS_LATERAL_MOVEMENT"
	AuditActionSSHPROXYSESSIONSTART             AuditAction = "SSH_PROXY_SESSION_START"
	AuditActionSSHPROXYSESSIONEND               AuditAction = "SSH_PROXY_SESSION_END"
	AuditActionSSHPROXYAUTHFAILURE              AuditAction = "SSH_PROXY_AUTH_FAILURE"
	AuditActionSSHPROXYTOKENISSUED              AuditAction = "SSH_PROXY_TOKEN_ISSUED"
	AuditActionDBTUNNELOPEN                     AuditAction = "DB_TUNNEL_OPEN"
	AuditActionDBTUNNELCLOSE                    AuditAction = "DB_TUNNEL_CLOSE"
	AuditActionDBTUNNELERROR                    AuditAction = "DB_TUNNEL_ERROR"
	AuditActionDBQUERYEXECUTED                  AuditAction = "DB_QUERY_EXECUTED"
	AuditActionDBQUERYBLOCKED                   AuditAction = "DB_QUERY_BLOCKED"
	AuditActionDBFIREWALLRULECREATE             AuditAction = "DB_FIREWALL_RULE_CREATE"
	AuditActionDBFIREWALLRULEUPDATE             AuditAction = "DB_FIREWALL_RULE_UPDATE"
	AuditActionDBFIREWALLRULEDELETE             AuditAction = "DB_FIREWALL_RULE_DELETE"
	AuditActionDBMASKINGPOLICYCREATE            AuditAction = "DB_MASKING_POLICY_CREATE"
	AuditActionDBMASKINGPOLICYUPDATE            AuditAction = "DB_MASKING_POLICY_UPDATE"
	AuditActionDBMASKINGPOLICYDELETE            AuditAction = "DB_MASKING_POLICY_DELETE"
	AuditActionDBQUERYFIREWALLALERT             AuditAction = "DB_QUERY_FIREWALL_ALERT"
	AuditActionDBQUERYPLANREQUESTED             AuditAction = "DB_QUERY_PLAN_REQUESTED"
	AuditActionDBQUERYAIOPTIMIZED               AuditAction = "DB_QUERY_AI_OPTIMIZED"
	AuditActionDBINTROSPECTIONREQUESTED         AuditAction = "DB_INTROSPECTION_REQUESTED"
	AuditActionDBSESSIONCONFIGUPDATED           AuditAction = "DB_SESSION_CONFIG_UPDATED"
	AuditActionTENANTUPDATEUSERPERMISSIONS      AuditAction = "TENANT_UPDATE_USER_PERMISSIONS"
	AuditActionVAULTNEEDSRECOVERY               AuditAction = "VAULT_NEEDS_RECOVERY"
	AuditActionVAULTRECOVERED                   AuditAction = "VAULT_RECOVERED"
	AuditActionVAULTEXPLICITRESET               AuditAction = "VAULT_EXPLICIT_RESET"
	AuditActionTUNNELMTLSREJECTED               AuditAction = "TUNNEL_MTLS_REJECTED"
	AuditActionSESSIONBLOCKED                   AuditAction = "SESSION_BLOCKED"
	AuditActionDBQUERYRATELIMITED               AuditAction = "DB_QUERY_RATE_LIMITED"
	AuditActionDBRATELIMITPOLICYCREATE          AuditAction = "DB_RATE_LIMIT_POLICY_CREATE"
	AuditActionDBRATELIMITPOLICYUPDATE          AuditAction = "DB_RATE_LIMIT_POLICY_UPDATE"
	AuditActionDBRATELIMITPOLICYDELETE          AuditAction = "DB_RATE_LIMIT_POLICY_DELETE"
	AuditActionAIQUERYGENERATED                 AuditAction = "AI_QUERY_GENERATED"
	AuditActionSFTPLIST                         AuditAction = "SFTP_LIST"
	AuditActionFILEUPLOAD                       AuditAction = "FILE_UPLOAD"
	AuditActionFILEDOWNLOAD                     AuditAction = "FILE_DOWNLOAD"
	AuditActionFILEDELETE                       AuditAction = "FILE_DELETE"
	AuditActionFILEMKDIR                        AuditAction = "FILE_MKDIR"
	AuditActionFILERENAME                       AuditAction = "FILE_RENAME"
	AuditActionFILELIST                         AuditAction = "FILE_LIST"
	AuditActionSESSIONPAUSE                     AuditAction = "SESSION_PAUSE"
	AuditActionSESSIONRESUME                    AuditAction = "SESSION_RESUME"
	AuditActionTUNNELEGRESSDENIED               AuditAction = "TUNNEL_EGRESS_DENIED"
)

func (e *AuditAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditAction(s)
	case string:
		*e = AuditAction(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditAction: %T", src)
	}
	return nil
}

type NullAuditAction struct {
	AuditAction AuditAction
	Valid       bool // Valid is true if AuditAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditAction) Scan(value interface{}) error {
	if value == nil {
		ns.AuditAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditAction), nil
}

type AuthProvider string

const (
	AuthProviderLOCAL     AuthProvider = "LOCAL"
	AuthProviderGOOGLE    AuthProvider = "GOOGLE"
	AuthProviderMICROSOFT AuthProvider = "MICROSOFT"
	AuthProviderGITHUB    AuthProvider = "GITHUB"
	AuthProviderOIDC      AuthProvider = "OIDC"
	AuthProviderSAML      AuthProvider = "SAML"
	AuthProviderLDAP      AuthProvider = "LDAP"
)

func (e *AuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProvider(s)
	case string:
		*e = AuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProvider: %T", src)
	}
	return nil
}

type NullAuthProvider struct {
	AuthProvider AuthProvider
	Valid        bool // Valid is true if AuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProvider), nil
}

type CheckoutStatus string

const (
	CheckoutStatusPENDING   CheckoutStatus = "PENDING"
	CheckoutStatusAPPROVED  CheckoutStatus = "APPROVED"
	CheckoutStatusREJECTED  CheckoutStatus = "REJECTED"
	CheckoutStatusEXPIRED   CheckoutStatus = "EXPIRED"
	CheckoutStatusCHECKEDIN CheckoutStatus = "CHECKED_IN"
)

func (e *CheckoutStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CheckoutStatus(s)
	case string:
		*e = CheckoutStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CheckoutStatus: %T", src)
	}
	return nil
}

type NullCheckoutStatus struct {
	CheckoutStatus CheckoutStatus
	Valid          bool // Valid is true if CheckoutStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCheckoutStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CheckoutStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CheckoutStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCheckoutStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CheckoutStatus), nil
}

type ConnectionType string

const (
	ConnectionTypeRDP      ConnectionType = "RDP"
	ConnectionTypeSSH      ConnectionType = "SSH"
	ConnectionTypeVNC      ConnectionType = "VNC"
	ConnectionTypeDATABASE ConnectionType = "DATABASE"
	ConnectionTypeDBTUNNEL ConnectionType = "DB_TUNNEL"
)

func (e *ConnectionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConnectionType(s)
	case string:
		*e = ConnectionType(s)
	default:
		return fmt.Errorf("unsupported scan type for ConnectionType: %T", src)
	}
	return nil
}

type NullConnectionType struct {
	ConnectionType ConnectionType
	Valid          bool // Valid is true if ConnectionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConnectionType) Scan(value interface{}) error {
	if value == nil {
		ns.ConnectionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConnectionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConnectionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConnectionType), nil
}

type DbQueryType string

const (
	DbQueryTypeSELECT DbQueryType = "SELECT"
	DbQueryTypeINSERT DbQueryType = "INSERT"
	DbQueryTypeUPDATE DbQueryType = "UPDATE"
	DbQueryTypeDELETE DbQueryType = "DELETE"
	DbQueryTypeDDL    DbQueryType = "DDL"
	DbQueryTypeOTHER  DbQueryType = "OTHER"
)

func (e *DbQueryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DbQueryType(s)
	case string:
		*e = DbQueryType(s)
	default:
		return fmt.Errorf("unsupported scan type for DbQueryType: %T", src)
	}
	return nil
}

type NullDbQueryType struct {
	DbQueryType DbQueryType
	Valid       bool // Valid is true if DbQueryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDbQueryType) Scan(value interface{}) error {
	if value == nil {
		ns.DbQueryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DbQueryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDbQueryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DbQueryType), nil
}

type ExternalVaultAuthMethod string

const (
	ExternalVaultAuthMethodTOKEN             ExternalVaultAuthMethod = "TOKEN"
	ExternalVaultAuthMethodAPPROLE           ExternalVaultAuthMethod = "APPROLE"
	ExternalVaultAuthMethodIAMACCESSKEY      ExternalVaultAuthMethod = "IAM_ACCESS_KEY"
	ExternalVaultAuthMethodIAMROLE           ExternalVaultAuthMethod = "IAM_ROLE"
	ExternalVaultAuthMethodCLIENTCREDENTIALS ExternalVaultAuthMethod = "CLIENT_CREDENTIALS"
	ExternalVaultAuthMethodMANAGEDIDENTITY   ExternalVaultAuthMethod = "MANAGED_IDENTITY"
	ExternalVaultAuthMethodSERVICEACCOUNTKEY ExternalVaultAuthMethod = "SERVICE_ACCOUNT_KEY"
	ExternalVaultAuthMethodWORKLOADIDENTITY  ExternalVaultAuthMethod = "WORKLOAD_IDENTITY"
	ExternalVaultAuthMethodCONJURAPIKEY      ExternalVaultAuthMethod = "CONJUR_API_KEY"
	ExternalVaultAuthMethodCONJURAUTHNK8S    ExternalVaultAuthMethod = "CONJUR_AUTHN_K8S"
)

func (e *ExternalVaultAuthMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExternalVaultAuthMethod(s)
	case string:
		*e = ExternalVaultAuthMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for ExternalVaultAuthMethod: %T", src)
	}
	return nil
}

type NullExternalVaultAuthMethod struct {
	ExternalVaultAuthMethod ExternalVaultAuthMethod
	Valid                   bool // Valid is true if ExternalVaultAuthMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExternalVaultAuthMethod) Scan(value interface{}) error {
	if value == nil {
		ns.ExternalVaultAuthMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExternalVaultAuthMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExternalVaultAuthMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExternalVaultAuthMethod), nil
}

type ExternalVaultType string

const (
	ExternalVaultTypeHASHICORPVAULT    ExternalVaultType = "HASHICORP_VAULT"
	ExternalVaultTypeAWSSECRETSMANAGER ExternalVaultType = "AWS_SECRETS_MANAGER"
	ExternalVaultTypeAZUREKEYVAULT     ExternalVaultType = "AZURE_KEY_VAULT"
	ExternalVaultTypeGCPSECRETMANAGER  ExternalVaultType = "GCP_SECRET_MANAGER"
	ExternalVaultTypeCYBERARKCONJUR    ExternalVaultType = "CYBERARK_CONJUR"
)

func (e *ExternalVaultType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExternalVaultType(s)
	case string:
		*e = ExternalVaultType(s)
	default:
		return fmt.Errorf("unsupported scan type for ExternalVaultType: %T", src)
	}
	return nil
}

type NullExternalVaultType struct {
	ExternalVaultType ExternalVaultType
	Valid             bool // Valid is true if ExternalVaultType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExternalVaultType) Scan(value interface{}) error {
	if value == nil {
		ns.ExternalVaultType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExternalVaultType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExternalVaultType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExternalVaultType), nil
}

type FirewallAction string

const (
	FirewallActionBLOCK FirewallAction = "BLOCK"
	FirewallActionALERT FirewallAction = "ALERT"
	FirewallActionLOG   FirewallAction = "LOG"
)

func (e *FirewallAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FirewallAction(s)
	case string:
		*e = FirewallAction(s)
	default:
		return fmt.Errorf("unsupported scan type for FirewallAction: %T", src)
	}
	return nil
}

type NullFirewallAction struct {
	FirewallAction FirewallAction
	Valid          bool // Valid is true if FirewallAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFirewallAction) Scan(value interface{}) error {
	if value == nil {
		ns.FirewallAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FirewallAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFirewallAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FirewallAction), nil
}

type GatewayDeploymentMode string

const (
	GatewayDeploymentModeSINGLEINSTANCE GatewayDeploymentMode = "SINGLE_INSTANCE"
	GatewayDeploymentModeMANAGEDGROUP   GatewayDeploymentMode = "MANAGED_GROUP"
)

func (e *GatewayDeploymentMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GatewayDeploymentMode(s)
	case string:
		*e = GatewayDeploymentMode(s)
	default:
		return fmt.Errorf("unsupported scan type for GatewayDeploymentMode: %T", src)
	}
	return nil
}

type NullGatewayDeploymentMode struct {
	GatewayDeploymentMode GatewayDeploymentMode
	Valid                 bool // Valid is true if GatewayDeploymentMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGatewayDeploymentMode) Scan(value interface{}) error {
	if value == nil {
		ns.GatewayDeploymentMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GatewayDeploymentMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGatewayDeploymentMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GatewayDeploymentMode), nil
}

type GatewayHealthStatus string

const (
	GatewayHealthStatusUNKNOWN     GatewayHealthStatus = "UNKNOWN"
	GatewayHealthStatusREACHABLE   GatewayHealthStatus = "REACHABLE"
	GatewayHealthStatusUNREACHABLE GatewayHealthStatus = "UNREACHABLE"
)

func (e *GatewayHealthStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GatewayHealthStatus(s)
	case string:
		*e = GatewayHealthStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GatewayHealthStatus: %T", src)
	}
	return nil
}

type NullGatewayHealthStatus struct {
	GatewayHealthStatus GatewayHealthStatus
	Valid               bool // Valid is true if GatewayHealthStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGatewayHealthStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GatewayHealthStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GatewayHealthStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGatewayHealthStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GatewayHealthStatus), nil
}

type GatewayType string

const (
	GatewayTypeGUACD      GatewayType = "GUACD"
	GatewayTypeSSHBASTION GatewayType = "SSH_BASTION"
	GatewayTypeMANAGEDSSH GatewayType = "MANAGED_SSH"
	GatewayTypeDBPROXY    GatewayType = "DB_PROXY"
)

func (e *GatewayType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GatewayType(s)
	case string:
		*e = GatewayType(s)
	default:
		return fmt.Errorf("unsupported scan type for GatewayType: %T", src)
	}
	return nil
}

type NullGatewayType struct {
	GatewayType GatewayType
	Valid       bool // Valid is true if GatewayType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGatewayType) Scan(value interface{}) error {
	if value == nil {
		ns.GatewayType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GatewayType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGatewayType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GatewayType), nil
}

type KeystrokePolicyAction string

const (
	KeystrokePolicyActionBLOCKANDTERMINATE KeystrokePolicyAction = "BLOCK_AND_TERMINATE"
	KeystrokePolicyActionALERTONLY         KeystrokePolicyAction = "ALERT_ONLY"
)

func (e *KeystrokePolicyAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KeystrokePolicyAction(s)
	case string:
		*e = KeystrokePolicyAction(s)
	default:
		return fmt.Errorf("unsupported scan type for KeystrokePolicyAction: %T", src)
	}
	return nil
}

type NullKeystrokePolicyAction struct {
	KeystrokePolicyAction KeystrokePolicyAction
	Valid                 bool // Valid is true if KeystrokePolicyAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKeystrokePolicyAction) Scan(value interface{}) error {
	if value == nil {
		ns.KeystrokePolicyAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KeystrokePolicyAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKeystrokePolicyAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KeystrokePolicyAction), nil
}

type LoadBalancingStrategy string

const (
	LoadBalancingStrategyROUNDROBIN       LoadBalancingStrategy = "ROUND_ROBIN"
	LoadBalancingStrategyLEASTCONNECTIONS LoadBalancingStrategy = "LEAST_CONNECTIONS"
)

func (e *LoadBalancingStrategy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LoadBalancingStrategy(s)
	case string:
		*e = LoadBalancingStrategy(s)
	default:
		return fmt.Errorf("unsupported scan type for LoadBalancingStrategy: %T", src)
	}
	return nil
}

type NullLoadBalancingStrategy struct {
	LoadBalancingStrategy LoadBalancingStrategy
	Valid                 bool // Valid is true if LoadBalancingStrategy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLoadBalancingStrategy) Scan(value interface{}) error {
	if value == nil {
		ns.LoadBalancingStrategy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LoadBalancingStrategy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLoadBalancingStrategy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LoadBalancingStrategy), nil
}

type ManagedInstanceStatus string

const (
	ManagedInstanceStatusPROVISIONING ManagedInstanceStatus = "PROVISIONING"
	ManagedInstanceStatusRUNNING      ManagedInstanceStatus = "RUNNING"
	ManagedInstanceStatusSTOPPED      ManagedInstanceStatus = "STOPPED"
	ManagedInstanceStatusERROR        ManagedInstanceStatus = "ERROR"
	ManagedInstanceStatusREMOVING     ManagedInstanceStatus = "REMOVING"
)

func (e *ManagedInstanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ManagedInstanceStatus(s)
	case string:
		*e = ManagedInstanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ManagedInstanceStatus: %T", src)
	}
	return nil
}

type NullManagedInstanceStatus struct {
	ManagedInstanceStatus ManagedInstanceStatus
	Valid                 bool // Valid is true if ManagedInstanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullManagedInstanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ManagedInstanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ManagedInstanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullManagedInstanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ManagedInstanceStatus), nil
}

type MaskingStrategy string

const (
	MaskingStrategyREDACT  MaskingStrategy = "REDACT"
	MaskingStrategyHASH    MaskingStrategy = "HASH"
	MaskingStrategyPARTIAL MaskingStrategy = "PARTIAL"
)

func (e *MaskingStrategy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaskingStrategy(s)
	case string:
		*e = MaskingStrategy(s)
	default:
		return fmt.Errorf("unsupported scan type for MaskingStrategy: %T", src)
	}
	return nil
}

type NullMaskingStrategy struct {
	MaskingStrategy MaskingStrategy
	Valid           bool // Valid is true if MaskingStrategy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaskingStrategy) Scan(value interface{}) error {
	if value == nil {
		ns.MaskingStrategy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaskingStrategy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaskingStrategy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaskingStrategy), nil
}

type NotificationType string

const (
	NotificationTypeCONNECTIONSHARED                 NotificationType = "CONNECTION_SHARED"
	NotificationTypeSHAREPERMISSIONUPDATED           NotificationType = "SHARE_PERMISSION_UPDATED"
	NotificationTypeSHAREREVOKED                     NotificationType = "SHARE_REVOKED"
	NotificationTypeSECRETSHARED                     NotificationType = "SECRET_SHARED"
	NotificationTypeSECRETSHAREREVOKED               NotificationType = "SECRET_SHARE_REVOKED"
	NotificationTypeSECRETEXPIRING                   NotificationType = "SECRET_EXPIRING"
	NotificationTypeSECRETEXPIRED                    NotificationType = "SECRET_EXPIRED"
	NotificationTypeTENANTINVITATION                 NotificationType = "TENANT_INVITATION"
	NotificationTypeRECORDINGREADY                   NotificationType = "RECORDING_READY"
	NotificationTypeIMPOSSIBLETRAVELDETECTED         NotificationType = "IMPOSSIBLE_TRAVEL_DETECTED"
	NotificationTypeSESSIONTERMINATEDPOLICYVIOLATION NotificationType = "SESSION_TERMINATED_POLICY_VIOLATION"
	NotificationTypeSECRETCHECKOUTREQUESTED          NotificationType = "SECRET_CHECKOUT_REQUESTED"
	NotificationTypeSECRETCHECKOUTAPPROVED           NotificationType = "SECRET_CHECKOUT_APPROVED"
	NotificationTypeSECRETCHECKOUTDENIED             NotificationType = "SECRET_CHECKOUT_DENIED"
	NotificationTypeSECRETCHECKOUTEXPIRED            NotificationType = "SECRET_CHECKOUT_EXPIRED"
	NotificationTypeLATERALMOVEMENTALERT             NotificationType = "LATERAL_MOVEMENT_ALERT"
	NotificationTypeTENANTVAULTKEYRECEIVED           NotificationType = "TENANT_VAULT_KEY_RECEIVED"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType
	Valid            bool // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type Permission string

const (
	PermissionREADONLY   Permission = "READ_ONLY"
	PermissionFULLACCESS Permission = "FULL_ACCESS"
)

func (e *Permission) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Permission(s)
	case string:
		*e = Permission(s)
	default:
		return fmt.Errorf("unsupported scan type for Permission: %T", src)
	}
	return nil
}

type NullPermission struct {
	Permission Permission
	Valid      bool // Valid is true if Permission is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPermission) Scan(value interface{}) error {
	if value == nil {
		ns.Permission, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Permission.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPermission) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Permission), nil
}

type RateLimitAction string

const (
	RateLimitActionREJECT  RateLimitAction = "REJECT"
	RateLimitActionLOGONLY RateLimitAction = "LOG_ONLY"
)

func (e *RateLimitAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RateLimitAction(s)
	case string:
		*e = RateLimitAction(s)
	default:
		return fmt.Errorf("unsupported scan type for RateLimitAction: %T", src)
	}
	return nil
}

type NullRateLimitAction struct {
	RateLimitAction RateLimitAction
	Valid           bool // Valid is true if RateLimitAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRateLimitAction) Scan(value interface{}) error {
	if value == nil {
		ns.RateLimitAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RateLimitAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRateLimitAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RateLimitAction), nil
}

type RecordingStatus string

const (
	RecordingStatusRECORDING RecordingStatus = "RECORDING"
	RecordingStatusCOMPLETE  RecordingStatus = "COMPLETE"
	RecordingStatusERROR     RecordingStatus = "ERROR"
)

func (e *RecordingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecordingStatus(s)
	case string:
		*e = RecordingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RecordingStatus: %T", src)
	}
	return nil
}

type NullRecordingStatus struct {
	RecordingStatus RecordingStatus
	Valid           bool // Valid is true if RecordingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecordingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RecordingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecordingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecordingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecordingStatus), nil
}

type RotationStatus string

const (
	RotationStatusSUCCESS RotationStatus = "SUCCESS"
	RotationStatusFAILED  RotationStatus = "FAILED"
	RotationStatusPENDING RotationStatus = "PENDING"
)

func (e *RotationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RotationStatus(s)
	case string:
		*e = RotationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RotationStatus: %T", src)
	}
	return nil
}

type NullRotationStatus struct {
	RotationStatus RotationStatus
	Valid          bool // Valid is true if RotationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRotationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RotationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RotationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRotationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RotationStatus), nil
}

type RotationTargetOS string

const (
	RotationTargetOSLINUX   RotationTargetOS = "LINUX"
	RotationTargetOSWINDOWS RotationTargetOS = "WINDOWS"
)

func (e *RotationTargetOS) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RotationTargetOS(s)
	case string:
		*e = RotationTargetOS(s)
	default:
		return fmt.Errorf("unsupported scan type for RotationTargetOS: %T", src)
	}
	return nil
}

type NullRotationTargetOS struct {
	RotationTargetOS RotationTargetOS
	Valid            bool // Valid is true if RotationTargetOS is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRotationTargetOS) Scan(value interface{}) error {
	if value == nil {
		ns.RotationTargetOS, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RotationTargetOS.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRotationTargetOS) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RotationTargetOS), nil
}

type RotationTrigger string

const (
	RotationTriggerSCHEDULED RotationTrigger = "SCHEDULED"
	RotationTriggerCHECKIN   RotationTrigger = "CHECKIN"
	RotationTriggerMANUAL    RotationTrigger = "MANUAL"
)

func (e *RotationTrigger) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RotationTrigger(s)
	case string:
		*e = RotationTrigger(s)
	default:
		return fmt.Errorf("unsupported scan type for RotationTrigger: %T", src)
	}
	return nil
}

type NullRotationTrigger struct {
	RotationTrigger RotationTrigger
	Valid           bool // Valid is true if RotationTrigger is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRotationTrigger) Scan(value interface{}) error {
	if value == nil {
		ns.RotationTrigger, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RotationTrigger.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRotationTrigger) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RotationTrigger), nil
}

type SecretScope string

const (
	SecretScopePERSONAL SecretScope = "PERSONAL"
	SecretScopeTEAM     SecretScope = "TEAM"
	SecretScopeTENANT   SecretScope = "TENANT"
)

func (e *SecretScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SecretScope(s)
	case string:
		*e = SecretScope(s)
	default:
		return fmt.Errorf("unsupported scan type for SecretScope: %T", src)
	}
	return nil
}

type NullSecretScope struct {
	SecretScope SecretScope
	Valid       bool // Valid is true if SecretScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSecretScope) Scan(value interface{}) error {
	if value == nil {
		ns.SecretScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SecretScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSecretScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SecretScope), nil
}

type SecretType string

const (
	SecretTypeLOGIN       SecretType = "LOGIN"
	SecretTypeSSHKEY      SecretType = "SSH_KEY"
	SecretTypeCERTIFICATE SecretType = "CERTIFICATE"
	SecretTypeAPIKEY      SecretType = "API_KEY"
	SecretTypeSECURENOTE  SecretType = "SECURE_NOTE"
)

func (e *SecretType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SecretType(s)
	case string:
		*e = SecretType(s)
	default:
		return fmt.Errorf("unsupported scan type for SecretType: %T", src)
	}
	return nil
}

type NullSecretType struct {
	SecretType SecretType
	Valid      bool // Valid is true if SecretType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSecretType) Scan(value interface{}) error {
	if value == nil {
		ns.SecretType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SecretType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSecretType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SecretType), nil
}

type SessionProtocol string

const (
	SessionProtocolSSH      SessionProtocol = "SSH"
	SessionProtocolRDP      SessionProtocol = "RDP"
	SessionProtocolVNC      SessionProtocol = "VNC"
	SessionProtocolSSHPROXY SessionProtocol = "SSH_PROXY"
	SessionProtocolDATABASE SessionProtocol = "DATABASE"
	SessionProtocolDBTUNNEL SessionProtocol = "DB_TUNNEL"
)

func (e *SessionProtocol) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionProtocol(s)
	case string:
		*e = SessionProtocol(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionProtocol: %T", src)
	}
	return nil
}

type NullSessionProtocol struct {
	SessionProtocol SessionProtocol
	Valid           bool // Valid is true if SessionProtocol is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionProtocol) Scan(value interface{}) error {
	if value == nil {
		ns.SessionProtocol, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionProtocol.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionProtocol) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionProtocol), nil
}

type SessionStatus string

const (
	SessionStatusACTIVE SessionStatus = "ACTIVE"
	SessionStatusIDLE   SessionStatus = "IDLE"
	SessionStatusCLOSED SessionStatus = "CLOSED"
	SessionStatusPAUSED SessionStatus = "PAUSED"
)

func (e *SessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatus(s)
	case string:
		*e = SessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatus: %T", src)
	}
	return nil
}

type NullSessionStatus struct {
	SessionStatus SessionStatus
	Valid         bool // Valid is true if SessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatus), nil
}

type SyncProvider string

const (
	SyncProviderNETBOX SyncProvider = "NETBOX"
)

func (e *SyncProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SyncProvider(s)
	case string:
		*e = SyncProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for SyncProvider: %T", src)
	}
	return nil
}

type NullSyncProvider struct {
	SyncProvider SyncProvider
	Valid        bool // Valid is true if SyncProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSyncProvider) Scan(value interface{}) error {
	if value == nil {
		ns.SyncProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SyncProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSyncProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SyncProvider), nil
}

type SyncStatus string

const (
	SyncStatusPENDING SyncStatus = "PENDING"
	SyncStatusRUNNING SyncStatus = "RUNNING"
	SyncStatusSUCCESS SyncStatus = "SUCCESS"
	SyncStatusPARTIAL SyncStatus = "PARTIAL"
	SyncStatusERROR   SyncStatus = "ERROR"
)

func (e *SyncStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SyncStatus(s)
	case string:
		*e = SyncStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SyncStatus: %T", src)
	}
	return nil
}

type NullSyncStatus struct {
	SyncStatus SyncStatus
	Valid      bool // Valid is true if SyncStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSyncStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SyncStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SyncStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSyncStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SyncStatus), nil
}

type TeamRole string

const (
	TeamRoleTEAMADMIN  TeamRole = "TEAM_ADMIN"
	TeamRoleTEAMEDITOR TeamRole = "TEAM_EDITOR"
	TeamRoleTEAMVIEWER TeamRole = "TEAM_VIEWER"
)

func (e *TeamRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeamRole(s)
	case string:
		*e = TeamRole(s)
	default:
		return fmt.Errorf("unsupported scan type for TeamRole: %T", src)
	}
	return nil
}

type NullTeamRole struct {
	TeamRole TeamRole
	Valid    bool // Valid is true if TeamRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeamRole) Scan(value interface{}) error {
	if value == nil {
		ns.TeamRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeamRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeamRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeamRole), nil
}

type TenantMembershipStatus string

const (
	TenantMembershipStatusPENDING  TenantMembershipStatus = "PENDING"
	TenantMembershipStatusACCEPTED TenantMembershipStatus = "ACCEPTED"
)

func (e *TenantMembershipStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantMembershipStatus(s)
	case string:
		*e = TenantMembershipStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantMembershipStatus: %T", src)
	}
	return nil
}

type NullTenantMembershipStatus struct {
	TenantMembershipStatus TenantMembershipStatus
	Valid                  bool // Valid is true if TenantMembershipStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantMembershipStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TenantMembershipStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantMembershipStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantMembershipStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantMembershipStatus), nil
}

type TenantRole string

const (
	TenantRoleOWNER      TenantRole = "OWNER"
	TenantRoleADMIN      TenantRole = "ADMIN"
	TenantRoleMEMBER     TenantRole = "MEMBER"
	TenantRoleOPERATOR   TenantRole = "OPERATOR"
	TenantRoleCONSULTANT TenantRole = "CONSULTANT"
	TenantRoleAUDITOR    TenantRole = "AUDITOR"
	TenantRoleGUEST      TenantRole = "GUEST"
)

func (e *TenantRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantRole(s)
	case string:
		*e = TenantRole(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantRole: %T", src)
	}
	return nil
}

type NullTenantRole struct {
	TenantRole TenantRole
	Valid      bool // Valid is true if TenantRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantRole) Scan(value interface{}) error {
	if value == nil {
		ns.TenantRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantRole), nil
}

type AccessPolicy struct {
	ID                   string
	TargetType           AccessPolicyTargetType
	TargetId             string
	AllowedTimeWindows   pgtype.Text
	RequireTrustedDevice bool
	RequireMfaStepUp     bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type ActiveSession struct {
	ID             string
	UserId         string
	ConnectionId   string
	GatewayId      pgtype.Text
	Protocol       SessionProtocol
	Status         SessionStatus
	SocketId       pgtype.Text
	GuacTokenHash  pgtype.Text
	StartedAt      time.Time
	LastActivityAt time.Time
	EndedAt        pgtype.Timestamp
	Metadata       []byte
	InstanceId     pgtype.Text
	IpAddress      pgtype.Text
	TenantId       pgtype.Text
}

type AgentRun struct {
	ID                    string
	TenantID              string
	DefinitionID          string
	Trigger               string
	Goals                 []byte
	RequestedCapabilities []byte
	Status                string
	RequiresApproval      bool
	RequestedAt           time.Time
	LastTransitionAt      time.Time
}

type AiDailyUsage struct {
	ID        string
	TenantId  string
	Date      pgtype.Date
	Count     int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AppConfig struct {
	Key       string
	Value     string
	UpdatedAt time.Time
}

type AuditLog struct {
	ID         string
	UserId     pgtype.Text
	Action     AuditAction
	TargetType pgtype.Text
	TargetId   pgtype.Text
	Details    []byte
	IpAddress  pgtype.Text
	CreatedAt  time.Time
	GatewayId  pgtype.Text
	GeoCity    pgtype.Text
	GeoCoords  []float64
	GeoCountry pgtype.Text
	Flags      []string
}

type Connection struct {
	ID                      string
	Name                    string
	Type                    ConnectionType
	Host                    string
	Port                    int32
	FolderId                pgtype.Text
	EncryptedUsername       pgtype.Text
	UsernameIV              pgtype.Text
	UsernameTag             pgtype.Text
	EncryptedPassword       pgtype.Text
	PasswordIV              pgtype.Text
	PasswordTag             pgtype.Text
	Description             pgtype.Text
	UserId                  string
	CreatedAt               time.Time
	UpdatedAt               time.Time
	EnableDrive             bool
	GatewayId               pgtype.Text
	IsFavorite              bool
	RdpSettings             []byte
	SshTerminalConfig       []byte
	TeamId                  pgtype.Text
	CredentialSecretId      pgtype.Text
	DomainIV                pgtype.Text
	DomainTag               pgtype.Text
	EncryptedDomain         pgtype.Text
	DefaultCredentialMode   pgtype.Text
	VncSettings             []byte
	DlpPolicy               []byte
	ExternalVaultProviderId pgtype.Text
	ExternalVaultPath       pgtype.Text
	SyncProfileId           pgtype.Text
	ExternalId              pgtype.Text
	DbSettings              []byte
	BastionConnectionId     pgtype.Text
	TargetDbHost            pgtype.Text
	TargetDbPort            pgtype.Int4
	DbType                  pgtype.Text
	TransferRetentionPolicy []byte
}

type DbAuditLog struct {
	ID              string
	UserId          string
	ConnectionId    string
	TenantId        pgtype.Text
	QueryText       string
	QueryType       DbQueryType
	TablesAccessed  []string
	RowsAffected    pgtype.Int4
	ExecutionTimeMs pgtype.Int4
	Blocked         bool
	BlockReason     pgtype.Text
	CreatedAt       time.Time
	ExecutionPlan   []byte
	SessionId       pgtype.Text
}

type DbFirewallRule struct {
	ID          string
	TenantId    string
	Name        string
	Pattern     string
	Action      FirewallAction
	Scope       pgtype.Text
	Description pgtype.Text
	Enabled     bool
	Priority    int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type DbMaskingPolicy struct {
	ID            string
	TenantId      string
	Name          string
	ColumnPattern string
	Strategy      MaskingStrategy
	ExemptRoles   []string
	Scope         pgtype.Text
	Description   pgtype.Text
	Enabled       bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type DbRateLimitPolicy struct {
	ID          string
	TenantId    string
	Name        string
	QueryType   NullDbQueryType
	WindowMs    int32
	MaxQueries  int32
	BurstMax    int32
	ExemptRoles []string
	Scope       pgtype.Text
	Action      RateLimitAction
	Enabled     bool
	Priority    int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type DeviceAuthCode struct {
	ID         string
	DeviceCode string
	UserCode   string
	UserId     pgtype.Text
	Authorized bool
	ExpiresAt  time.Time
	Interval   int32
	ClientId   string
	CreatedAt  time.Time
}

type ExternalSecretShare struct {
	ID              string
	SecretId        string
	CreatedByUserId string
	TokenHash       string
	EncryptedData   string
	DataIV          string
	DataTag         string
	HasPin          bool
	PinSalt         pgtype.Text
	ExpiresAt       time.Time
	MaxAccessCount  pgtype.Int4
	AccessCount     int32
	SecretType      SecretType
	SecretName      string
	IsRevoked       bool
	CreatedAt       time.Time
	TokenSalt       pgtype.Text
}

type ExternalVaultProvider struct {
	ID                   string
	TenantId             string
	Name                 string
	ServerUrl            string
	AuthMethod           ExternalVaultAuthMethod
	Namespace            pgtype.Text
	MountPath            string
	EncryptedAuthPayload string
	AuthPayloadIV        string
	AuthPayloadTag       string
	CaCertificate        pgtype.Text
	CacheTtlSeconds      int32
	Enabled              bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ProviderType         ExternalVaultType
}

type Folder struct {
	ID        string
	Name      string
	ParentId  pgtype.Text
	UserId    string
	SortOrder int32
	CreatedAt time.Time
	UpdatedAt time.Time
	TeamId    pgtype.Text
}

type Gateway struct {
	ID                       string
	Name                     string
	Type                     GatewayType
	Host                     string
	Port                     int32
	DeploymentMode           GatewayDeploymentMode
	Description              pgtype.Text
	IsDefault                bool
	TenantId                 string
	CreatedById              string
	EncryptedUsername        pgtype.Text
	UsernameIV               pgtype.Text
	UsernameTag              pgtype.Text
	EncryptedPassword        pgtype.Text
	PasswordIV               pgtype.Text
	PasswordTag              pgtype.Text
	CreatedAt                time.Time
	UpdatedAt                time.Time
	LastCheckedAt            pgtype.Timestamp
	LastError                pgtype.Text
	LastHealthStatus         GatewayHealthStatus
	LastLatencyMs            pgtype.Int4
	MonitorIntervalMs        int32
	MonitoringEnabled        bool
	EncryptedSshKey          pgtype.Text
	SshKeyIV                 pgtype.Text
	SshKeyTag                pgtype.Text
	ApiPort                  pgtype.Int4
	InactivityTimeoutSeconds int32
	DesiredReplicas          int32
	IsManaged                bool
	AutoScale                bool
	LastScaleAction          pgtype.Timestamp
	MaxReplicas              int32
	MinReplicas              int32
	ScaleDownCooldownSeconds int32
	SessionsPerInstance      int32
	TemplateId               pgtype.Text
	PublishPorts             bool
	LbStrategy               LoadBalancingStrategy
	TunnelEnabled            bool
	EncryptedTunnelToken     pgtype.Text
	TunnelTokenIV            pgtype.Text
	TunnelTokenTag           pgtype.Text
	TunnelTokenHash          pgtype.Text
	TunnelConnectedAt        pgtype.Timestamp
	TunnelLastHeartbeat      pgtype.Timestamp
	TunnelClientVersion      pgtype.Text
	TunnelClientIp           pgtype.Text
	TunnelClientCert         pgtype.Text
	TunnelClientCertExp      pgtype.Timestamp
	TunnelClientKey          pgtype.Text
	TunnelClientKeyIV        pgtype.Text
	TunnelClientKeyTag       pgtype.Text
	EgressPolicy             []byte
}

type GatewayTemplate struct {
	ID                       string
	Name                     string
	Type                     GatewayType
	Host                     string
	Port                     int32
	DeploymentMode           GatewayDeploymentMode
	Description              pgtype.Text
	ApiPort                  pgtype.Int4
	AutoScale                bool
	MinReplicas              int32
	MaxReplicas              int32
	SessionsPerInstance      int32
	ScaleDownCooldownSeconds int32
	MonitoringEnabled        bool
	MonitorIntervalMs        int32
	InactivityTimeoutSeconds int32
	TenantId                 string
	CreatedById              string
	CreatedAt                time.Time
	UpdatedAt                time.Time
	PublishPorts             bool
	LbStrategy               LoadBalancingStrategy
}

type KeystrokePolicy struct {
	ID            string
	TenantId      string
	Name          string
	Description   pgtype.Text
	Action        KeystrokePolicyAction
	RegexPatterns []string
	Enabled       bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ManagedGatewayInstance struct {
	ID                  string
	GatewayId           string
	ContainerId         string
	ContainerName       string
	Host                string
	Port                int32
	Status              ManagedInstanceStatus
	OrchestratorType    string
	HealthStatus        pgtype.Text
	LastHealthCheck     pgtype.Timestamp
	ErrorMessage        pgtype.Text
	CreatedAt           time.Time
	UpdatedAt           time.Time
	ConsecutiveFailures int32
	ApiPort             pgtype.Int4
	TunnelProxyHost     pgtype.Text
	TunnelProxyPort     pgtype.Int4
}

type MemoryItem struct {
	ID           string
	NamespaceKey string
	Content      string
	Summary      string
	Metadata     []byte
	CreatedAt    time.Time
}

type MemoryNamespace struct {
	ID           string
	NamespaceKey string
	TenantID     string
	Scope        string
	PrincipalID  string
	AgentID      string
	RunID        string
	WorkflowID   string
	MemoryType   string
	Name         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Notification struct {
	ID        string
	UserId    string
	Type      NotificationType
	Message   string
	Read      bool
	RelatedId pgtype.Text
	CreatedAt time.Time
}

type NotificationPreference struct {
	ID        string
	UserId    string
	Type      NotificationType
	InApp     bool
	Email     bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OAuthAccount struct {
	ID             string
	UserId         string
	Provider       AuthProvider
	ProviderUserId string
	ProviderEmail  pgtype.Text
	AccessToken    pgtype.Text
	RefreshToken   pgtype.Text
	CreatedAt      time.Time
	UpdatedAt      time.Time
	SamlAttributes []byte
}

type OpenTab struct {
	ID           string
	UserId       string
	ConnectionId string
	SortOrder    int32
	IsActive     bool
	CreatedAt    time.Time
}

type OrchestratorConnection struct {
	ID           string
	Name         string
	Kind         string
	Scope        string
	Endpoint     string
	Namespace    string
	Labels       []byte
	Capabilities []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type PasswordRotationLog struct {
	ID           string
	SecretId     string
	Status       RotationStatus
	Trigger      RotationTrigger
	TargetOS     RotationTargetOS
	TargetHost   string
	TargetUser   string
	ErrorMessage pgtype.Text
	DurationMs   pgtype.Int4
	InitiatedBy  pgtype.Text
	CreatedAt    time.Time
}

type PendingVaultKeyDistribution struct {
	ID                      string
	TenantId                string
	TargetUserId            string
	EncryptedTenantVaultKey string
	TenantVaultKeyIV        string
	TenantVaultKeyTag       string
	DistributorUserId       string
	CreatedAt               time.Time
}

type PrismaMigration struct {
	ID                string
	Checksum          string
	FinishedAt        pgtype.Timestamptz
	MigrationName     string
	Logs              pgtype.Text
	RolledBackAt      pgtype.Timestamptz
	StartedAt         time.Time
	AppliedStepsCount int32
}

type RefreshToken struct {
	ID              string
	Token           string
	UserId          string
	ExpiresAt       time.Time
	CreatedAt       time.Time
	RevokedAt       pgtype.Timestamp
	TokenFamily     string
	IpUaHash        pgtype.Text
	FamilyCreatedAt time.Time
}

type SecretCheckoutRequest struct {
	ID              string
	SecretId        pgtype.Text
	ConnectionId    pgtype.Text
	RequesterId     string
	ApproverId      pgtype.Text
	Status          CheckoutStatus
	DurationMinutes int32
	Reason          pgtype.Text
	ExpiresAt       pgtype.Timestamp
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type SessionRecording struct {
	ID           string
	SessionId    pgtype.Text
	UserId       string
	ConnectionId string
	Protocol     SessionProtocol
	FilePath     string
	FileSize     pgtype.Int4
	Duration     pgtype.Int4
	Format       string
	Status       RecordingStatus
	CreatedAt    time.Time
	CompletedAt  pgtype.Timestamp
	Height       pgtype.Int4
	Width        pgtype.Int4
}

type SharedConnection struct {
	ID                string
	ConnectionId      string
	SharedWithUserId  string
	SharedByUserId    string
	Permission        Permission
	EncryptedUsername pgtype.Text
	UsernameIV        pgtype.Text
	UsernameTag       pgtype.Text
	EncryptedPassword pgtype.Text
	PasswordIV        pgtype.Text
	PasswordTag       pgtype.Text
	CreatedAt         time.Time
	DomainIV          pgtype.Text
	DomainTag         pgtype.Text
	EncryptedDomain   pgtype.Text
}

type SharedSecret struct {
	ID               string
	SecretId         string
	SharedWithUserId string
	SharedByUserId   string
	Permission       Permission
	EncryptedData    string
	DataIV           string
	DataTag          string
	CreatedAt        time.Time
}

type SshKeyPair struct {
	ID                   string
	TenantId             string
	EncryptedPrivateKey  string
	PrivateKeyIV         string
	PrivateKeyTag        string
	PublicKey            string
	Fingerprint          string
	Algorithm            string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	AutoRotateEnabled    bool
	ExpiresAt            pgtype.Timestamp
	LastAutoRotatedAt    pgtype.Timestamp
	RotationIntervalDays int32
}

type SyncLog struct {
	ID            string
	SyncProfileId string
	Status        SyncStatus
	StartedAt     time.Time
	CompletedAt   pgtype.Timestamp
	Details       []byte
	TriggeredBy   string
}

type SyncProfile struct {
	ID                string
	Name              string
	TenantId          string
	Provider          SyncProvider
	Config            []byte
	EncryptedApiToken string
	ApiTokenIV        string
	ApiTokenTag       string
	CronExpression    pgtype.Text
	Enabled           bool
	TeamId            pgtype.Text
	LastSyncAt        pgtype.Timestamp
	LastSyncStatus    NullSyncStatus
	LastSyncDetails   []byte
	CreatedById       string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type SystemSecret struct {
	ID                     string
	Name                   string
	CurrentVersion         int32
	EncryptedValue         string
	ValueIV                string
	ValueTag               string
	PreviousEncryptedValue pgtype.Text
	PreviousValueIV        pgtype.Text
	PreviousValueTag       pgtype.Text
	RotatedAt              pgtype.Timestamp
	AutoRotate             bool
	RotationIntervalDays   int32
	Distributed            bool
	TargetService          pgtype.Text
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type Team struct {
	ID          string
	Name        string
	Description pgtype.Text
	TenantId    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type TeamMember struct {
	ID                    string
	TeamId                string
	UserId                string
	Role                  TeamRole
	EncryptedTeamVaultKey pgtype.Text
	TeamVaultKeyIV        pgtype.Text
	TeamVaultKeyTag       pgtype.Text
	JoinedAt              time.Time
	ExpiresAt             pgtype.Timestamp
}

type Tenant struct {
	ID                            string
	Name                          string
	Slug                          string
	CreatedAt                     time.Time
	UpdatedAt                     time.Time
	HasTenantVaultKey             bool
	DefaultSessionTimeoutSeconds  int32
	MfaRequired                   bool
	VaultAutoLockMaxMinutes       pgtype.Int4
	DlpDisableCopy                bool
	DlpDisablePaste               bool
	DlpDisableDownload            bool
	DlpDisableUpload              bool
	IpAllowlistEnabled            bool
	IpAllowlistMode               string
	IpAllowlistEntries            []string
	EnforcedConnectionSettings    []byte
	MaxConcurrentSessions         int32
	AbsoluteSessionTimeoutSeconds int32
	TunnelDefaultEnabled          bool
	TunnelAutoTokenRotation       bool
	TunnelTokenRotationDays       int32
	TunnelRequireForRemote        bool
	TunnelTokenMaxLifetimeDays    pgtype.Int4
	TunnelAgentAllowedCidrs       []string
	LoginRateLimitWindowMs        pgtype.Int4
	LoginRateLimitMaxAttempts     pgtype.Int4
	AccountLockoutThreshold       pgtype.Int4
	AccountLockoutDurationMs      pgtype.Int4
	ImpossibleTravelSpeedKmh      pgtype.Int4
	JwtExpiresInSeconds           pgtype.Int4
	JwtRefreshExpiresInSeconds    pgtype.Int4
	VaultDefaultTtlMinutes        pgtype.Int4
	FileUploadMaxSizeBytes        pgtype.Int4
	RecordingEnabled              bool
	RecordingRetentionDays        pgtype.Int4
	TunnelCaCert                  pgtype.Text
	TunnelCaCertFingerprint       pgtype.Text
	TunnelCaKey                   pgtype.Text
	TunnelCaKeyIV                 pgtype.Text
	TunnelCaKeyTag                pgtype.Text
	UserDriveQuotaBytes           pgtype.Int4
}

type TenantAiBackend struct {
	ID              string
	TenantId        string
	Name            string
	Provider        string
	EncryptedApiKey pgtype.Text
	ApiKeyIV        pgtype.Text
	ApiKeyTag       pgtype.Text
	BaseUrl         pgtype.Text
	DefaultModel    pgtype.Text
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type TenantAiConfig struct {
	ID                     string
	TenantId               string
	Provider               string
	EncryptedApiKey        pgtype.Text
	ApiKeyIV               pgtype.Text
	ApiKeyTag              pgtype.Text
	ModelId                string
	BaseUrl                pgtype.Text
	MaxTokensPerRequest    int32
	DailyRequestLimit      int32
	Enabled                bool
	CreatedAt              time.Time
	UpdatedAt              time.Time
	QueryGenerationBackend pgtype.Text
	QueryGenerationModel   pgtype.Text
	QueryOptimizerEnabled  bool
	QueryOptimizerBackend  pgtype.Text
	QueryOptimizerModel    pgtype.Text
	Temperature            float64
	TimeoutMs              int32
}

type TenantMember struct {
	ID                  string
	TenantId            string
	UserId              string
	Role                TenantRole
	IsActive            bool
	JoinedAt            time.Time
	UpdatedAt           time.Time
	ExpiresAt           pgtype.Timestamp
	PermissionOverrides []byte
	Status              TenantMembershipStatus
}

type TenantVaultMember struct {
	ID                      string
	TenantId                string
	UserId                  string
	EncryptedTenantVaultKey string
	TenantVaultKeyIV        string
	TenantVaultKeyTag       string
	CreatedAt               time.Time
}

type User struct {
	ID                        string
	Email                     string
	PasswordHash              pgtype.Text
	VaultSalt                 pgtype.Text
	EncryptedVaultKey         pgtype.Text
	VaultKeyIV                pgtype.Text
	VaultKeyTag               pgtype.Text
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	AvatarData                pgtype.Text
	EmailVerified             bool
	EmailVerifyExpiry         pgtype.Timestamp
	EmailVerifyToken          pgtype.Text
	PhoneNumber               pgtype.Text
	PhoneVerified             bool
	RdpDefaults               []byte
	SmsMfaEnabled             bool
	SmsOtpExpiresAt           pgtype.Timestamp
	SmsOtpHash                pgtype.Text
	SshDefaults               []byte
	TotpEnabled               bool
	TotpSecret                pgtype.Text
	Username                  pgtype.Text
	VaultSetupComplete        bool
	FailedLoginAttempts       int32
	LockedUntil               pgtype.Timestamp
	EncryptedTotpSecret       pgtype.Text
	TotpSecretIV              pgtype.Text
	TotpSecretTag             pgtype.Text
	WebauthnEnabled           bool
	VaultAutoLockMinutes      pgtype.Int4
	Enabled                   bool
	EncryptedVaultRecoveryKey pgtype.Text
	PasswordResetExpiry       pgtype.Timestamp
	PasswordResetTokenHash    pgtype.Text
	VaultRecoveryKeyIV        pgtype.Text
	VaultRecoveryKeySalt      pgtype.Text
	VaultRecoveryKeyTag       pgtype.Text
	DomainName                pgtype.Text
	DomainPasswordIV          pgtype.Text
	DomainPasswordTag         pgtype.Text
	DomainUsername            pgtype.Text
	EmailChangeCodeNewHash    pgtype.Text
	EmailChangeCodeOldHash    pgtype.Text
	EmailChangeExpiry         pgtype.Timestamp
	EncryptedDomainPassword   pgtype.Text
	PendingEmail              pgtype.Text
	NotifDndEnabled           bool
	NotifQuietHoursStart      pgtype.Text
	NotifQuietHoursEnd        pgtype.Text
	NotifQuietHoursTimezone   pgtype.Text
	VaultNeedsRecovery        bool
}

type VaultFolder struct {
	ID        string
	Name      string
	ParentId  pgtype.Text
	UserId    string
	Scope     SecretScope
	TeamId    pgtype.Text
	TenantId  pgtype.Text
	SortOrder int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type VaultSecret struct {
	ID                    string
	Name                  string
	Description           pgtype.Text
	Type                  SecretType
	Scope                 SecretScope
	UserId                string
	TeamId                pgtype.Text
	TenantId              pgtype.Text
	FolderId              pgtype.Text
	EncryptedData         string
	DataIV                string
	DataTag               string
	Metadata              []byte
	Tags                  []string
	IsFavorite            bool
	ExpiresAt             pgtype.Timestamp
	CurrentVersion        int32
	CreatedAt             time.Time
	UpdatedAt             time.Time
	TargetRotationEnabled bool
	RotationIntervalDays  int32
	LastRotatedAt         pgtype.Timestamp
	PwnedCount            int32
}

type VaultSecretVersion struct {
	ID            string
	SecretId      string
	Version       int32
	EncryptedData string
	DataIV        string
	DataTag       string
	ChangedBy     string
	ChangeNote    pgtype.Text
	CreatedAt     time.Time
}

type WebAuthnCredential struct {
	ID           string
	UserId       string
	CredentialId string
	PublicKey    string
	Counter      int64
	Transports   []string
	DeviceType   pgtype.Text
	BackedUp     bool
	FriendlyName string
	Aaguid       pgtype.Text
	LastUsedAt   pgtype.Timestamp
	CreatedAt    time.Time
}
