#!/usr/bin/env bash
# Prints the .env configuration lines for full mTLS development setup.
# Usage: ./infrastructure/configure-dev-mtls.sh >> /path/to/.env

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cat <<EOF

# === Full mTLS Configuration (generated by infrastructure/configure-dev-mtls.sh) ===
# All services share a single CA: dev-certs/ca.pem
SPIFFE_TRUST_DOMAIN=arsenale.local

# Express + guacamole-lite server TLS
SERVER_TLS_CERT=$REPO_ROOT/dev-certs/server/server-cert.pem
SERVER_TLS_KEY=$REPO_ROOT/dev-certs/server/server-key.pem

# Tunnel mTLS server
TUNNEL_SERVER_CERT=$REPO_ROOT/dev-certs/tunnel/server-cert.pem
TUNNEL_SERVER_KEY=$REPO_ROOT/dev-certs/tunnel/server-key.pem
TUNNEL_SERVER_CA=$REPO_ROOT/dev-certs/ca.pem

# Dedicated cache backend mTLS (client certs for Node.js → Go gRPC)
CACHE_KV_URL=localhost:6380
CACHE_KV_TLS_CA=$REPO_ROOT/dev-certs/ca.pem
CACHE_KV_TLS_CERT=$REPO_ROOT/dev-certs/gocache-cache/client-cert.pem
CACHE_KV_TLS_KEY=$REPO_ROOT/dev-certs/gocache-cache/client-key.pem

# Dedicated pubsub backend mTLS (client certs for Node.js / sidecars → Go gRPC)
CACHE_PUBSUB_URL=localhost:6480
CACHE_PUBSUB_TLS_CA=$REPO_ROOT/dev-certs/ca.pem
CACHE_PUBSUB_TLS_CERT=$REPO_ROOT/dev-certs/gocache-pubsub/client-cert.pem
CACHE_PUBSUB_TLS_KEY=$REPO_ROOT/dev-certs/gocache-pubsub/client-key.pem

# PostgreSQL SSL
DATABASE_URL=postgresql://arsenale:arsenale_password@localhost:5432/arsenale?sslmode=require

# guacenc sidecar HTTPS + auth
GUACENC_USE_TLS=true
GUACENC_SERVICE_URL=https://localhost:3003
GUACENC_TLS_CERT=$REPO_ROOT/dev-certs/guacenc/server-cert.pem
GUACENC_TLS_KEY=$REPO_ROOT/dev-certs/guacenc/server-key.pem
GUACENC_AUTH_TOKEN=$(openssl rand -hex 32)

# Gateway API TLS
GATEWAY_API_USE_TLS=true

# Client URLs (HTTPS)
CLIENT_URL=https://localhost:3000
EOF
