-- AlterTable
ALTER TABLE "Gateway" ADD COLUMN IF NOT EXISTS "encryptedSshKey" TEXT;
ALTER TABLE "Gateway" ADD COLUMN IF NOT EXISTS "sshKeyIV" TEXT;
ALTER TABLE "Gateway" ADD COLUMN IF NOT EXISTS "sshKeyTag" TEXT;
